---
apiVersion: v1
kind: Namespace
metadata:
  name: saas

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: saas
  name: saas
  labels:
    app: saas
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saas
      environment: development
  template:
    metadata:
      labels:
        app: saas
        environment: development
    spec:
      containers:
        - name: ghost-blog
          image: ghost:5
          ports:
            - containerPort: 2368
          env:
            - name: database__client
              value: sqlite3
          readinessProbe:
            httpGet:
              path: /
              port: 2368
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  namespace: saas
  name: saas
spec:
  type: ClusterIP # 🔥 important for Ingress
  selector:
    app: saas
    environment: development
  ports:
    - port: 80
      targetPort: 2368

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: saas
  name: saas-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: saas
                port:
                  number: 80
